# 服务端口
server:
  port: 9171
# Spring配置
spring:
  mvc:
    static-path-pattern: /**
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/DB_music?zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: jia204109
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxWait: 60000
  #Json配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #文件上传相关配置
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

#mybatis 配置
mybatis:
  type-aliases-package: com.jimi.music.entity
  mapper-locations: classpath:mapper/*.xml

#是否开启推荐算法
useRecommend: false
